### PR TITLE
Add `IRazorTemplateEngine` & allow dependency injection through constructor

### PR DESCRIPTION
**Pull request by pbolduc**
I removed the static initialization that should help address #25 and #46. The Azure Function is not working yet.

### CODE REVIEW

**Comment by pbolduc** [comment]
I have added back the static methods. However, I have introduced `IRazorTemplateEngine` and an implementation class `RazorTemplateEngineImpl`. The static RazorTemplateEngine will lazily create an instance of these with an internal service collection. If callers want to use their own service collection, then they can call `services.AddRazorTemplating();` in their startup / DI registration and inject an instance of IRazorTemplateEngine where ever they require.

**Comment by soundaranbu** [comment]
Hey @pbolduc, your contributions are really welcomed! It helps to fix the long standing issues.
I'll go over these on this weekend & merge it if everything works fine.

**Comment by pbolduc** [comment]
> I'll go over these on this weekend & merge it if everything works fine.

Please comment on this PR if you have any concerns. I guess one area not covered is docs.  I tried to make the asp.net type examples use the interface. And the other examples that typically do not use DI, use the static version.  I also do not like the class name `RazorTemplateEngineImpl` but struggled with coming up something cleaner without re-using `RazorTemplateEngine` (class can't have static and non-static methods with same signatures).

**Comment by soundaranbu** [comment]
Hey @pbolduc, I looked at it. It's good that it solves most problems. Even I attempted a similar solution earlier. But dropped due to the breaking change it introduced. However, we can't keep growing the issues either. So, it's inevitable.

So let me bring up the breaking changes being introduced here in this PR:
## Breaking Change 1:
If the users require DI, then they will need to use the instance of `IRazorTemplateEngine` from DI instead of `RazorTemplateEngine` static class. The users will need to update their code accordingly.
### Before:
```cs
ServiceCollection services = new ServiceCollection();
services.AddRazorTemplating();
var html = await RazorTemplateEngine.RenderAsync("~/Views/Index.cshtml");
```

### After:
In console applications:
```cs
ServiceCollection services = new ServiceCollection();
services.AddRazorTemplating();
var razorTemplateEngine = services.BuildServiceProvider().GetRequiredService<IRazorTemplateEngine>();

var html = await razorTemplateEngine.RenderAsync("~/Views/Index.cshtml");
```
In ASP.NET Core or Worker Service applications:
```cs
builder.Services.AddRazorTemplating();
```

```cs
public class MyService {
    private readonly IRazorTemplateEngine _engine;

    public MyService (IRazorTemplateEngine engine)
    {
        _engine = engine;
    }

    public async Task Index()
    {
        var renderedString = await _engine.RenderAsync("/Views/Home/Index.cshtml");
        // do something with renderedString
    }
}
```

## Breaking Change 2:
Because of the unification of 3 APIs into 1, there's a breaking change with the following pattern where the model is null & viewData is present. We were needed to pass the generic type param as `object`. Now it's not required to pass any generic type param.

Before:
```cs
var html = await RazorTemplateEngine.RenderAsync<object>("~/Views/ExampleViewWithLayout.cshtml", null, viewData);
```

After:
```cs
var html = await RazorTemplateEngine.RenderAsync("~/Views/ExampleViewWithLayout.cshtml", null, viewData);
```

What's your thought on this?

Between for naming the new class, we can use something like `RazorTemplateEngineRenderer`. How does that sound?

**Comment by pbolduc** [comment]
> Hey @pbolduc, I looked at it. It's good that it solves most problems. Even I attempted a similar solution earlier. But dropped due to the breaking change it introduced. However, we can't keep growing the issues either. So, it's inevitable.
> 
> So let me bring up the breaking changes being introduced here in this PR:
> 
> ## Breaking Change 1:
> If the users require DI, then they will need to use the instance of `IRazorTemplateEngine` from DI instead of `RazorTemplateEngine` static class. The users will need to update their code accordingly.
> 
> ### Before:
> ```cs
> ServiceCollection services = new ServiceCollection();
> services.AddRazorTemplating();
> var html = await RazorTemplateEngine.RenderAsync("~/Views/Index.cshtml");
> ```
> 
> ### After:
> In console applications:
> 
> ```cs
> ServiceCollection services = new ServiceCollection();
> services.AddRazorTemplating();
> var razorTemplateEngine = services.BuildServiceProvider().GetRequiredService<IRazorTemplateEngine>();
> 
> var html = await razorTemplateEngine.RenderAsync("~/Views/Index.cshtml");
> ```
> 
> In ASP.NET Core or Worker Service applications:
> 
> ```cs
> builder.Services.AddRazorTemplating();
> ```
> 
> ```cs
> public class MyService {
>     private readonly IRazorTemplateEngine _engine;
> 
>     public MyService (IRazorTemplateEngine engine)
>     {
>         _engine = engine;
>     }
> 
>     public async Task Index()
>     {
>         var renderedString = await _engine.RenderAsync("/Views/Home/Index.cshtml");
>         // do something with renderedString
>     }
> }
> ```
> 
> ## Breaking Change 2:
> Because of the unification of 3 APIs into 1, there's a breaking change with the following pattern where the model is null & viewData is present. We were needed to pass the generic type param as `object`. Now it's not required to pass any generic type param.
> 
> Before:
> 
> ```cs
> var html = await RazorTemplateEngine.RenderAsync<object>("~/Views/ExampleViewWithLayout.cshtml", null, viewData);
> ```
> 
> After:
> 
> ```cs
> var html = await RazorTemplateEngine.RenderAsync("~/Views/ExampleViewWithLayout.cshtml", null, viewData);
> ```
> 
> What's your thought on this?
> 
> Between for naming the new class, we can use something like `RazorTemplateEngineRenderer`. How does that sound?

I just pushed a change to remove `Breaking Change 1`. If the caller calls `AddRazorTemplating`, then we save their service collection inside the static class. When creating the instance, if the service collection was added by calling `AddRazorTemplating`, then we use that service collection. If `AddRazorTemplating` was not called, we create our own service collection, call `AddRazorTemplating` and create the instance.

**Comment by pbolduc** [comment]
I wonder if we could create a build and push out a `prerelease` preview version with these changes to nuget. This would allow others to test.

**Comment by soundaranbu** [comment]
Hey @pbolduc, yes we could but the test related to the breaking change 1 is not passing in my local. I thought of checking it on this weekend. But if you have time, can you take a look? 
We'll need to create another test class which contains the same test cases as in the main branch.

**Comment by pbolduc** [comment]
> Hey @pbolduc, yes we could but the test related to the breaking change 1 is not passing in my local. 

What test is not passing? Unit test or the examples?  I just ran all the unit tests and they pass here...

image

**Comment by pbolduc** [comment]
> Hey @pbolduc, yes we could but the test related to the breaking change 1 is not passing in my local.

I just pushed a commit that adds some unit tests and should resolve the issues you experienced. The main fix., specifically with unit tests, is to ensure `RazorTemplateEngine.UseServiceCollection(services);` is called after all registrations are complete. A problem when multiple unit tests were all trying to set the service collection at the same time, the registration process is incomplete. This is sort of an edge case specific to unit tests. In a real app, it would only be registered once.

**Comment by soundaranbu** [comment]
Ok this user is running the test cases parallel ly https://github.com/soundaranbu/Razor.Templating.Core/issues/46#issue-1353995030. So they will still face some issue if static class is used with dependency injection. Instead they need to use the instance of `IRazorTemplateEngine`. Is that right?

**Comment by pbolduc** [comment]
> Ok this user is running the test cases parallel ly [#46 (comment)](https://github.com/soundaranbu/Razor.Templating.Core/issues/46#issue-1353995030). So they will still face some issue if static class is used with dependency injection. Instead they need to use the instance of `IRazorTemplateEngine`. Is that right?

It **should** just work with the static class now after my last commit. 

But with the IRazorTemplateEngine implementation, they could remove the rendering if they like from a lot of their tests. Services that render stuff out, could be injected a mock (Moq) IRazorTemplateEngine and ensure the parameters are passed correctly. Then they could add additional tests to ensure each template gets rendered out correctly with varying the input data as per their requirements.

**Comment by soundaranbu** [comment]
Ok alright. I've added the test case that I was talking about. It's basically bringing back the original test cases which were in place before this PR. Only that particular test case is failing. The fun part is that it passes if we run it separately in Visual Studio. But it fails only when we run all the test cases at once.

**Comment by pbolduc** [comment]
I just looked at the failing test, `RenderView_WithServiceInjection`. The reason this fails when running all the tests is concurrent initialization of the static instance. Each test is creating their own ServiceCollection and initializing the static instance. It is a race condition on initialization. By design, the static instance should only be initialized once for the life time of the application. So once the "singleton" is created, other initializations will fail. The only way I can see creating reliable tests is adding some internal lock and reset functions on the static instance to support testing scenarios.

**Comment by soundaranbu** [comment]
Ok, I've fixed it with a simple flag. Now all the test cases are passing & there are no breaking changes.

**Comment by pbolduc** [comment]
> Ok, I've fixed it with a simple flag. Now all the test cases are passing & there are no breaking changes.

I added a xUnit test fixture to isolate each unit test that uses the shared instance. I removed your tracking if the service collection changed cause it is not required when using the test fixture.

**Comment by soundaranbu** [comment]
Ok, this works. I'll publish a prerelease package this weekend (or even earlier) so that we can start testing.

**Comment by pbolduc** [comment]
I guess an enhancement would be to ensure that if the instance has already been initialized, that calls to set the service collection will fail. Something like:

```cs
        internal static void UseServiceCollection(IServiceCollection services)
        {
            if (_instance.IsValueCreated)
            {
                throw new InvalidOperationException("Cannot set service collection, RazorTemplateEngine has already been initialized.");
            }

            _services = services;
        }
```

**Comment by pbolduc** [comment]
I just added the change above. It will help prevent people from running into issues.  When calling AddRazorTemplating, you can optional opt out of registering to the static class. By default, the static class will be registered with the service collection.  For example, in the testing of RazorTemplateEngineRenderer, we use

```cs
            services.AddRazorTemplating(opts => opts.UseStaticRazorTemplateEngine = false);
            var serviceProvider = services.BuildServiceProvider();

            _sut = new RazorTemplateEngineRenderer(serviceProvider);
```
because we are not testing the static class. I also added parameter check to the static class to avoid creating the instance if the user has not supplied a view name correctly.

**Comment by pbolduc** [comment]
Let me know if you would like help writing up some documentation on the changes. It is always hard getting up dated documentation.

**Comment by soundaranbu** [comment]
I refactored the code a little bit. Some of your ideas were great. But I wanted to keep it more realistic and simple. I will publish a prerelease based on this. Let's see how it's perceived.
Some key refactorings:
- `RazorTemplateEngineRenderer` is made internal. We don't want the users to create their own instances with it. They need to either use the static class or `IRazorTemplateEngine` with DI
- Test cases are combined together
- We don't want to introduce the `UseStaticRazorTemplateEngine` option at this point. I hope in real-world scenarios there won't be much friction with non-static & static instances. This can be revisited in the future if required.
- Rebuild the static `IRazorTemplateEngine` instance whenever there's a new service collection set instead of throwing an exception. I understand the parallel initialization concern. Since all our tests are passing already, I feel it's a rare case scenario and we encourage the users to do the DI setup only once per application (which should be the case). Again, if it causes any issues, we'll come back to this. 

On the documentation part, you are welcome to contribute :) But I already made some changes to it. If you feel it can be improved please send a separate PR after merging this one.

**Review by soundaranbu — APPROVED** [review]

**Comment by soundaranbu** [comment]
Hey @pbolduc, these changes are now released as [NuGet package](https://github.com/soundaranbu/Razor.Templating.Core/releases/tag/v1.8.0-rc.1).

Great work! Thanks for all your contributions!

**Pull request merged**
