### PR TITLE
Added option to RenderPartialAsync when you don't need a layout page …

### PR DESCRIPTION
**Pull request by mobiletonster**
…around the partial view.

Sometimes you may want to render content as a partial view rather than a complete view with the layout page. This pull request provides an option to RenderPartialAsync using the templating engine.

### CODE REVIEW

**Comment by soundaranbu** [comment]
Hi @mobiletonster, I'm thinking if we could add the flag in the same `RenderAsync` method? 

`int renderAsPartial = false` 

Please suggest me if it's a better and simple way.

**Comment by mobiletonster** [comment]
> 

I considered that originally, but I think having a separate render method makes the intent clearer. The only issue I have with having a separate method is there is some code duplication that could possibly be refactored, however, there is a tradeoff between over abstracting for the sake of DRY or having some minimal duplication of code. Ultimately, it is your library, so you have the final say.

**Comment by mobiletonster** [comment]
I refactored the code slightly to remove some code duplication and while the public facing API still shows a separate render method for partials, the internal implementation uses a flag and calls the same render method internally.

**Comment by soundaranbu** [comment]
Thanks @mobiletonster, I'll review this tomorrow and let you know. If everything is fine, I'll make a pre release NuGet package.

**Comment by soundaranbu** [comment]
Hi @mobiletonster, I've one question. Does it not work for you when we can already set `Layout = null` to avoid rendering the layout?

image

**Comment by mobiletonster** [comment]
> Hi @mobiletonster, I've one question. Does it not work for you when we can already set `Layout = null` to avoid rendering the layout?
> 
> image

I think that breaks the pattern for when you do embed the partial in another page that wants the layout and isn't a recommended approach for shared partials.

**Comment by soundaranbu** [comment]
Agreed. I'll review this & let you know.

**Comment by mobiletonster** [comment]
I plan to put together a video and posting a tutorial on youtube for the library to show when and how you would want to use the RenderPartialAsync method for common web applications, in particular I have a group of real-time applications that use SignalR to martial updates to the Web UI and by far, this library is the best available to support these really cool real-time apps.

**Review by soundaranbu — APPROVED** [review]

**Comment by soundaranbu** [comment]
> I plan to put together a video and posting a tutorial on youtube for the library to show when and how you would want to use the RenderPartialAsync method for common web applications, in particular I have a group of real-time applications that use SignalR to martial updates to the Web UI and by far, this library is the best available to support these really cool real-time apps.

That would be great. Looking forward!

**Pull request merged**
